generateinputs: input1 input2 input3 input4
	

input1:makeSOM.py
	python makeSOM.py 10 > input1

input2:makeSOM.py
	python makeSOM.py 100 > input2

input3:makeSOM.py
	python makeSOM.py 1000 > input3

input4:makeSOM.py
	python makeSOM.py 10000 > input4

input5:makeSOM.py
	python makeSOM.py 100000 > input5